#!/usr/bin/env node
// Dumps the local images table to db/seed-images.sql as INSERT statements.
// Run via: npm run db:dump-images

const { execSync }    = require("child_process");
const { writeFileSync } = require("fs");

let raw;
try {
  raw = execSync(
    "wrangler d1 execute petrosani --local --json --command \"SELECT id, pin_id, mime, chunk_index, data FROM images ORDER BY id, chunk_index\"",
    { encoding: "utf8" }
  );
} catch (e) {
  console.error("Failed to query local D1:", e.message);
  process.exit(1);
}

const [{ results }] = JSON.parse(raw);

if (!results || results.length === 0) {
  writeFileSync("db/seed-images.sql", "-- No images to seed\n");
  console.log("No images found — wrote empty db/seed-images.sql");
  process.exit(0);
}

const inserts = results.map(({ id, pin_id, mime, chunk_index, data }) =>
  `INSERT INTO images (id, pin_id, mime, chunk_index, data) VALUES ('${id}', '${pin_id}', '${mime}', ${chunk_index}, '${data}');`
);

const output = [
  "-- Auto-generated by scripts/dump-images.js",
  "-- Run 'npm run db:dump-images' to regenerate",
  "",
  ...inserts,
  "",
].join("\n");

writeFileSync("db/seed-images.sql", output);
console.log(`Dumped ${results.length} image(s) to db/seed-images.sql`);
